#!/bin/bash
#
# Auto-generated mosaic script for clustered PlanetScope scenes
# Generated by cluster_and_mosaic.py
#

# Configuration
OTB_MOSAIC="/Users/macbook/OTB-8.1.2-Darwin64/bin/otbcli_Mosaic"
INPUT_DIR="."
OUTPUT_DIR="./mosaic_clustered"

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "=========================================="
echo "PlanetScope Mosaic - Auto-Clustered Blocks"
echo "Scenes ordered by cloud cover (highest first = bottom)"
echo "=========================================="
echo "Input directory: $INPUT_DIR"
echo "Output directory: $OUTPUT_DIR"
echo ""

# Function to mosaic a cluster
mosaic_cluster() {
    local cluster=$1
    shift
    local files=("$@")

    echo "Processing Cluster $cluster (${#files[@]} scenes)..."

    # Build input list
    local input_files=""
    for f in "${files[@]}"; do
        input_files="$input_files \"$INPUT_DIR/$f\""
    done

    local output_file="$OUTPUT_DIR/mosaic_${cluster}.tif"

    # Run OTB Mosaic
    eval "$OTB_MOSAIC" \
        -il $input_files \
        -out "\"$output_file\"" uint16 \
        -comp.feather large \
        -harmo.method band \
        -harmo.cost rmse \
        -interpolator nn \
        -nodata 0 \
        2>&1 | grep -v "^WARN"

    if [ -f "$output_file" ]; then
        echo "  -> Created: $output_file"
    else
        echo "  -> ERROR creating mosaic for cluster $cluster"
    fi
    echo ""
}

# cluster_1: 84 scenes (cloud cover: 46% -> 0%)
mosaic_cluster cluster_1 \
    "20251201_043640_94_24ee_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043244_37_250b_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041917_42_253b_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042643_84_2541_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043637_56_24f4_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041915_10_253b_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042502_44_2501_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042504_59_2501_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_044523_53_24f5_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043339_66_2535_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042648_48_2541_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043639_54_24f4_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041912_79_253b_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043624_33_24f3_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042334_67_250d_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_044051_58_24df_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043725_39_24f2_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043816_16_24d1_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042636_88_2541_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043729_34_24f2_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043915_46_24fd_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042401_69_2518_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043618_08_24f6_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042650_80_2541_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043242_21_250b_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043641_52_24f4_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043723_42_24f2_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043727_37_24f2_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043818_20_24d1_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042641_52_2541_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_044059_52_24df_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042228_96_250e_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042332_53_250d_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043616_10_24f6_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042624_57_251e_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042757_24_2527_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042500_29_2501_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042824_61_2500_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042226_81_250e_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043622_32_24f3_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043638_91_24ee_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_044101_51_24df_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042224_66_250e_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042926_32_2547_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042359_57_2518_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043721_44_24f2_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042639_20_2541_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042824_10_251f_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041733_25_251d_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042731_40_2539_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042937_79_2547_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043635_58_24f4_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043620_31_24f3_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041731_06_251d_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042622_26_251e_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043814_12_24d1_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043636_89_24ee_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041726_67_251d_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041728_87_251d_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042933_20_2547_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_044521_75_24f5_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_044049_59_24df_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042633_82_251e_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042754_95_2527_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042935_49_2547_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042458_14_2501_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042636_14_251e_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042729_10_2539_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042801_83_2527_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043614_11_24f6_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043404_23_24de_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043913_48_24fd_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042357_45_2518_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042804_12_2527_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042631_51_251e_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042752_65_2527_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042806_42_2527_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042808_71_2527_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042822_67_2500_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042924_03_2547_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043633_60_24f4_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_043719_47_24f2_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_044519_96_24f5_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_043618_30_24f3_3B_AnalyticMS_SR_file_format.tif"

# cluster_5: 10 scenes (cloud cover: 34% -> 0%)
mosaic_cluster cluster_5 \
    "20251201_041113_62_2526_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_040859_82_253a_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_040857_54_253a_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041111_54_2526_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042648_03_24df_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042646_04_24df_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041001_61_253f_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041003_90_253f_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_042650_02_24df_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041408_84_251b_3B_AnalyticMS_SR_file_format.tif"

# cluster_2: 9 scenes (cloud cover: 34% -> 0%)
mosaic_cluster cluster_2 \
    "20251201_042312_02_24fb_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042314_01_24fb_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041742_79_24ee_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_040913_53_253a_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041744_81_24ee_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042315_99_24fb_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041747_03_24ee_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_042317_98_24fb_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_040915_81_253a_3B_AnalyticMS_SR_file_format.tif"

# cluster_3: 5 scenes (cloud cover: 50% -> 0%)
mosaic_cluster cluster_3 \
    "20251129_041856_82_252b_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041627_53_24da_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041625_40_24da_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041854_53_252b_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041852_23_252b_3B_AnalyticMS_SR_file_format.tif"

# cluster_6: 5 scenes (cloud cover: 48% -> 3%)
mosaic_cluster cluster_6 \
    "20251201_041415_93_2507_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041324_82_251b_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041413_82_2507_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041411_71_2507_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041322_91_251b_3B_AnalyticMS_SR_file_format.tif"

# cluster_7: 4 scenes (cloud cover: 36% -> 19%)
mosaic_cluster cluster_7 \
    "20251201_041653_10_24da_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041657_36_24da_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041655_23_24da_3B_AnalyticMS_SR_file_format.tif" \
    "20251201_041659_49_24da_3B_AnalyticMS_SR_file_format.tif"

# cluster_4: 2 scenes (cloud cover: 34% -> 25%)
mosaic_cluster cluster_4 \
    "20251129_041905_99_252b_3B_AnalyticMS_SR_file_format.tif" \
    "20251129_041903_70_252b_3B_AnalyticMS_SR_file_format.tif"

echo "=========================================="
echo "Mosaic complete!"
echo "Output files in: $OUTPUT_DIR"
ls -lh "$OUTPUT_DIR"/mosaic_*.tif 2>/dev/null || echo "No output files found"
echo "=========================================="
